### PR TITLE
Feat - Add Name and Email Generation

### PR DESCRIPTION
**Pull request by WashingtonKK**
Signed-off-by: WashingtonKK <washingtonkigan@gmail.com>

# What type of PR is this?

This PR adds a feature to generate names separated with a space and an email along with it.
The email contains the domain @example.com and the email is constructed by joining the names.

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Dependency Update

## Related Tickets & Documents

- No issue

## Added/updated tests?

- [ ] I need help with writing tests

## Added/updated documentation

- [ ] I need help with writing documentation

## Summary by CodeRabbit

- **New Features**
  - Added functionality to generate names and emails based on gender.
  - Enhanced the name generation process to include associated email addresses.

### CODE REVIEW

**Comment by rodneyosodo** [comment]
This is unnecessary since you can use the suffix option to generate an email when generating the names or initializing the generator. This is an example of how to do it

```go
package main

import (
	"fmt"

	"github.com/0x6flab/namegenerator"
)

func main() {
	generator := namegenerator.NewGenerator().WithSuffix("@gmail.com")
	name := generator.Generate()
	fmt.Println(name)

	generator = namegenerator.NewGenerator()
	name = generator.Generate(namegenerator.WithSuffix("@gmail.com"))
	fmt.Println(name)
}
```


@WashingtonKK Does this fix your issue?

**Comment by WashingtonKK** [comment]
No it does not, 
Normally there are times you want names that have the form: `FirstName` `LastName` and not `FirstName-LastName`

**Comment by rodneyosodo** [comment]
Do you want to generate an email with only the `FirstName` i.e. `FirstName`+`Suffix`?

**Comment by rodneyosodo** [comment]
The issue you are reuqesting has been solved by https://github.com/0x6flab/namegenerator/pull/33

**Pull request closed without merging**
